modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/sepals/issues"
license = "GPLv3"

[[mods]]
modId = "sepals"
version = "${version}"
displayName = "Sepals"
authors = "cao_awa"
description = '''
Sepals is an extremely radical and experimental optimization for Minecraft server performances.
'''
#logoFile = ""

[[dependencies.sepals]]
modId = "neoforge"
type = "required"
versionRange = "[21.6.8-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sepals]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = ["sepals.mixins.json", "sepals-neoforged.mixins.json"]
